### ISSUE TITLE
open the app store when you click on an application in the "installed apps" list

### ISSUE THREAD

**Issue by Wjxfi** [d4rken-org/octi#11]
The pname+ application code should work when you click on any application in the "installed apps" list.

it allows you to open an application by package name through any app store (f-droid, play market, droid-ify, aurora store, etc.).

https://github.com/bndeff/pname

https://play.google.com/store/apps/details?id=app.pname

This is for downloading apps from another device

just use his code

**Comment by d4rken** [comment]
Added by #61
