### ISSUE TITLE
[Feture request] Add some option to unlock pro on degoogled phones

### ISSUE THREAD

**Issue by egigoka** [d4rken-org/octi#21]
I've successfully bought this app on phone with Google services, but on other phone without Google services i got an error 
"Error: IllegalStateException
Unknown SKU,no details available"

I know, it's not a small task, but it will be cool thing to do.

**Comment by d4rken** [comment]
For ungoogled phone I'd say just use the FOSS build and sponsor me on GitHub ❤️ .

I've tried 3rd party store/payment/unlock methods (e.g. apps.darken.eu) and while do-able, the amount of effort it takes do this is just way too much in comparison to how many people use it. Additionally it's not a one time effort, but on-going.

Out of scope, sorry.
