### ISSUE TITLE
The app disappeared from Play Store

### ISSUE THREAD

**Issue by JasonHK** [d4rken-org/octi#28]
Did Google play dumb again?

**Comment by d4rken** [comment]
Should be back by now?

**Comment by Helpful-Neko** [comment]
Google is dumb like that sometimes. They're the reason I've switched to more open sourced applications lol

**Comment by d4rken** [comment]
Was likely this:
https://www.reddit.com/r/androiddev/comments/15xj0ow/dev_account_terminated_after_12_years_for/

Resolved :)
