### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by SyafaHadyan** [d4rken-org/octi#33]
# Feature Suggestions

1. Alert or notify any other devices if battery is low.
2. Media control.
3. Send files.
4. Locate device or find device.
5. Turn off or lock device.
6. Send last location to other devices if the phone is about to die.

**Comment by d4rken** [comment]
Thanks for the feedback!

> Alert or notify any other devices if battery is low.

See #45

> Media control.

See #8

> Send files.

Out of scope for Octi.

> Locate device or find device.
> Send last location to other devices if the phone is about to die.

Locating the device itself is out of scope.
This is more of a job for Google's find my device network.

> Turn off or lock device.

Not possible without root :frowning: 

If you have other ideas, please create one ticket per idea, so they can be individually discussed. Or create a discussion: https://github.com/d4rken-org/octi/discussions
