### ISSUE TITLE
Octi widget stays blank

### ISSUE THREAD

**Issue by MemphisReins29** [d4rken-org/octi#46]
Hi. I am a big fan of your Octi Pro app!! Recently I have been experiencing an issue with the widget though, the widget isn't showing anything, it's just black, it been this way for a few weeks now. Please we 222² Octi widget stays blank

**Comment by d4rken** [comment]
What's your device? Android version? Octi version?

Does Octi itself show the data correctly?

**Comment by d4rken** [comment]
I can't reproduce this, the widget is working for me.

**Comment by d4rken** [comment]
Need a way to reproduce this or a debuglog :frowning:
